version: 2.1
orbs:
  azure-aks: circleci/azure-aks@0.2.1
jobs:
    login-and-development-deploy:
        executor: azure-aks/azure-docker
        steps:
            - checkout
            - run:
                command: az login -u ${USER} -p ${PASS}
                name: Sign In to Azure CLI
            - azure-aks/update-kubeconfig-with-credentials:
                cluster-name: cluster
                install-kubectl: true
                resource-group: Ubuntu
            - run:
                command: kubectl delete configmap app1-page --namespace ingress-basic
                name: Deleted last configmap
            - run:
                command: kubectl delete configmap app2-page --namespace ingress-basic
                name: Deleted last configmap
            - run:
                command: kubectl create configmap app1-page --from-file=app1/ --namespace ingress-basic
                name: Deleted update configmap
            - run:
                command: kubectl create configmap app2-page --from-file=app2/ --namespace ingress-basic
                name: Deleted update configmap
            - run:
                command: kubectl scale --replicas=0 deployment app1 --namespace ingress-basic
                name: Remove all the replicas
            - run:
                command: kubectl scale --replicas=2 deployment app1 --namespace ingress-basic
                name: Restart the replicas
    approval-job:
    login-and-production-deploy:
        executor: azure-aks/azure-docker
        steps:
            - checkout
            - run:
                command: az login -u ${USER} -p ${PASS}
                name: Sign In to Azure CLI
            - azure-aks/update-kubeconfig-with-credentials:
                cluster-name: production
                install-kubectl: true
                resource-group: Produc
            - run:
                command: kubectl delete configmap app1-page --namespace ingress-basic
                name: Deleted last configmap
            - run:
                command: kubectl delete configmap app2-page --namespace ingress-basic
                name: Deleted last configmap
            - run:
                command: kubectl create configmap app1-page --from-file=app1/ --namespace ingress-basic
                name: Deleted update configmap
            - run:
                command: kubectl create configmap app2-page --from-file=app2/ --namespace ingress-basic
                name: Deleted update configmap
            - run:
                command: kubectl scale --replicas=0 deployment app1 --namespace ingress-basic
                name: Remove all the replicas
            - run:
                command: kubectl scale --replicas=1 deployment app1 --namespace ingress-basic
                name: Restart the replicas
workflows:
    build-and-test:
      jobs:
        - login-and-development-deploy:
            filters:
                branches:
                    only: circleci-project-setup
        - approval-job:
            type: approval
            requires:
                - login-and-development-deploy
            filters:
              branches:
                  only: circleci-project-setup
        - login-and-production-deploy:
            filters:
                branches:
                    only: circleci-project-setup
            requires:
                - approval-job